### 기본 URL
@baseUrl = http://localhost:8080


### 크루 등록 - BE 트랙
POST {{baseUrl}}/crews
Content-Type: application/json

{
  "githubId": "sauter001",
  "nickname": "이승재",
  "track": "BE"
}


### 크루 등록 - FE 트랙
POST {{baseUrl}}/crews
Content-Type: application/json

{
  "githubId": "frontend-user",
  "nickname": "프론트엔드크루",
  "track": "FE"
}


### 크루 등록 - ANDROID 트랙
POST {{baseUrl}}/crews
Content-Type: application/json

{
  "githubId": "android-user",
  "nickname": "안드로이드크루",
  "track": "ANDROID"
}


### 크루 등록 - SOFT 트랙
POST {{baseUrl}}/crews
Content-Type: application/json

{
  "githubId": "soft-user",
  "nickname": "소프트스킬크루",
  "track": "SOFT"
}


### 크루 등록 - 중복 githubId 에러 케이스
POST {{baseUrl}}/crews
Content-Type: application/json

{
  "githubId": "sauter001",
  "nickname": "중복사용자",
  "track": "BE"
}
